version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      python-api-dependencies:
        patterns:
          - "*"
